<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="DESKTOP-DT85C65" failures="2" tests="4" name="Test(failed)" time="0.179" errors="0" timestamp="2022-06-25T18:17:56 IST">
  <testcase classname="TestNG_Failed_XML.Class2" name="TC7" time="0.022">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at TestNG_Failed_XML.Class2.TC7(Class2.java:23)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TC7 -->
  <testcase classname="TestNG_Failed_XML.Class2" name="TC5" time="0.008">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at TestNG_Failed_XML.Class2.TC5(Class2.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TC5 -->
  <testcase classname="TestNG_Failed_XML.Class1" name="TC1" time="0.012"/>
  <testcase classname="TestNG_Failed_XML.Class1" name="TC3" time="0.004"/>
  <testcase classname="TestNG_Failed_XML.Class2" name="TC6" time="0.0">
    <ignored/>
  </testcase> <!-- TC6 -->
  <testcase classname="TestNG_Failed_XML.Class2" name="TC8" time="0.0">
    <ignored/>
  </testcase> <!-- TC8 -->
  <testcase classname="TestNG_Failed_XML.Class1" name="TC2" time="0.0">
    <ignored/>
  </testcase> <!-- TC2 -->
  <testcase classname="TestNG_Failed_XML.Class1" name="TC4" time="0.0">
    <ignored/>
  </testcase> <!-- TC4 -->
</testsuite> <!-- Test(failed) -->
